### ISSUE TITLE
Prepare for 1.0 release

### ISSUE THREAD

**Issue by snewcomer** [adopted-ember-addons/ember-infinity#281]
- [x] allow beta branch to simmer a bit longer
- [x] #284 

Post 1.1
- [ ] replace more pretender mocks with Mirage (essentially the same thing...just a bit more re-useable)
- [ ] Put together an example with a Phoenix / Elixir backend + pagination (as an example)
- [ ] deprecate the following in `1.1` - boundParameters, updateInfinityModel, _notifyInfinityModelUpdated

Let me know if anybody has anybody has issues or questions about removing the above deprecated methods for the 1.0 release!  📦

**Comment by snewcomer** [comment]
One consideration out there is to change the `infinity-loader` service name to `infinity`.  Just throwing this out there if anybody has opinions or thoughts for the [service](https://github.com/ember-infinity/ember-infinity#service-methods).  It does seem to convey better what it does (more than just loads more records.  Also various methods to mutate the array) and may expand to do more things in the future.

@Duder-onomy Any thoughts?

**Comment by thomassnielsen** [comment]
I'm currently looking at different infinite scroll libraries, and this one showed up at the top of EmberObserver. I see that the readme mentions a stable 1.0 by the end of May. I recon that might not be the case, judging from the checkboxes in this issue? Should we expect major changes in the near future if we use the current beta release?

**Comment by hhff** [comment]
Yes!  It's on my todo list :)

h
