### ISSUE TITLE
devDependencies and dependencies are out of date 

### ISSUE THREAD

**Issue by takshch** [adopted-ember-addons/ember-infinity#453]
# Description
devDependencies and dependencies are out of date

https://david-dm.org/ember-infinity/ember-infinity#info=devDependencies
https://david-dm.org/ember-infinity/ember-infinity#info=dependencies

**Comment by snewcomer** [comment]
Hi @takshch!  PRs are always welcome.  I'll see if I have time this weekend to do this as well.

**Comment by jahrock** [comment]
This has been resolved with latest release.

@RobbieTheWagner we should be able to close this issue.
