### ISSUE TITLE
Will the project be supported for ember 4? 

### ISSUE THREAD

**Issue by a1723** [adopted-ember-addons/ember-infinity#469]
Will the project be supported? can't get ember-ace 3.0.0 to work with ember-infinity 2.3.0 on ember-cli 4.10.0
Without ember-infinity ember-ace works as well.

**Comment by jahrock** [comment]
Hi @a1723 
There are two open PR's to add support for ember 4/5.

We would be very thankful for a review.
Thank you in advance.

- [Upgrade to Ember 4 #470](https://github.com/ember-infinity/ember-infinity/pull/470)
- [chore: makes it Ember 5 compatible #471](https://github.com/ember-infinity/ember-infinity/pull/471)

**Comment by mansona** [comment]
This is now fixed by #470 👍 just waiting for a release of that PR but it should be soon
